# See Dependabot documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "MahanRahmati"
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "MahanRahmati"
  - package-ecosystem: gradle
    directory: "/example/android"
    schedule:
      interval: "weekly"
    reviewers:
      - "MahanRahmati"
  - package-ecosystem: "bundler"
    directory: "/android"
    schedule:
      interval: "weekly"
    reviewers:
      - "MahanRahmati"