name: arna
description: Arna is a set of widgets designed to be simple and easy to use for building applications with Flutter.
version: 1.0.6
homepage: https://github.com/MahanRahmati/Arna

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  arna_animations: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Bold.otf
          weight: 700
        - asset: fonts/Inter-Light.otf
          weight: 300
        - asset: fonts/Inter-Medium.otf
          weight: 500
        - asset: fonts/Inter-Regular.otf
          weight: 400
